name: Deploy to EC2
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Create SSH key
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.PRIVATE_KEY }}" > private_key.pem
          sudo chmod 600 private_key.pem
          
      # Debug step (remove in production)
      - name: Debug private key
        run: |
          if [ -f private_key.pem ]; then
            ls -l private_key.pem
            head -n 1 private_key.pem
          fi
          
      - name: Deploy to EC2
        run: |
          scp -i private_key.pem -o StrictHostKeyChecking=no -r ./* ${{ secrets.HOST }}:~/app/
          ssh -i private_key.pem -o StrictHostKeyChecking=no ${{ secrets.HOST }} 'cd ~/app && chmod +x deploy.sh && ./deploy.sh'